### ISSUE TITLE
Parsing error on duckduckgo

### ISSUE THREAD

**Issue by y9yk** [y9yk/blog-post-writer-using-multi-agents-ai-system#10]
## Issue Details
---
아래 에러스택 참고해서 해결필요

```
Traceback (most recent call last):
  File "/Users/y9yk/dev/crew/.venv/lib/python3.10/site-packages/duckduckgo_search/duckduckgo_search.py", line 114, in _get_url
    resp = self.client.request(method, url, params=params, content=content, data=data)
TypeError: argument 'params': 'tuple' object cannot be converted to 'PyString'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/y9yk/dev/crew/main.py", line 127, in <module>
    execute()
  File "/Users/y9yk/dev/crew/.venv/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/Users/y9yk/dev/crew/.venv/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/Users/y9yk/dev/crew/.venv/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/y9yk/dev/crew/.venv/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Users/y9yk/dev/crew/main.py", line 120, in execute
    loop.run_until_complete(processor.run())
  File "/Users/y9yk/.pyenv/versions/3.10.8/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/Users/y9yk/dev/crew/main.py", line 92, in run
    await self._process_sub_topics(
  File "/Users/y9yk/dev/crew/main.py", line 52, in _process_sub_topics
    await self.subtopic_agent.research()
  File "/Users/y9yk/dev/crew/blog_poster/agents/blog_agent.py", line 295, in research
    self.context = await asyncio.gather(
  File "/Users/y9yk/dev/crew/blog_poster/agents/blog_agent.py", line 147, in _process_sub_query
    search_results = self.retreiver.search(query=sub_query)
  File "/Users/y9yk/dev/crew/blog_poster/retriever/providers/duckduckgo.py", line 27, in search
    ddgs_gen = self.ddg.text(
  File "/Users/y9yk/dev/crew/.venv/lib/python3.10/site-packages/duckduckgo_search/duckduckgo_search.py", line 213, in text
    results = self._text_api(keywords, region, safesearch, timelimit, max_results)
  File "/Users/y9yk/dev/crew/.venv/lib/python3.10/site-packages/duckduckgo_search/duckduckgo_search.py", line 300, in _text_api
    raise e
  File "/Users/y9yk/dev/crew/.venv/lib/python3.10/site-packages/duckduckgo_search/duckduckgo_search.py", line 297, in _text_api
    for r in self._executor.map(_text_api_page, slist):
  File "/Users/y9yk/.pyenv/versions/3.10.8/lib/python3.10/concurrent/futures/_base.py", line 621, in result_iterator
    yield _result_or_cancel(fs.pop())
  File "/Users/y9yk/.pyenv/versions/3.10.8/lib/python3.10/concurrent/futures/_base.py", line 319, in _result_or_cancel
    return fut.result(timeout)
  File "/Users/y9yk/.pyenv/versions/3.10.8/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/Users/y9yk/.pyenv/versions/3.10.8/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/Users/y9yk/.pyenv/versions/3.10.8/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/y9yk/dev/crew/.venv/lib/python3.10/site-packages/duckduckgo_search/duckduckgo_search.py", line 275, in _text_api_page
    resp_content = self._get_url("GET", "https://links.duckduckgo.com/d.js", params=payload)
  File "/Users/y9yk/dev/crew/.venv/lib/python3.10/site-packages/duckduckgo_search/duckduckgo_search.py", line 119, in _get_url
    raise DuckDuckGoSearchException(f"{url} {type(ex).__name__}: {ex}") from ex
duckduckgo_search.exceptions.DuckDuckGoSearchException: https://links.duckduckgo.com/d.js TypeError: argument 'params': 'tuple' object cannot be converted to 'PyString'
```

**Comment by y9yk** [comment]
closed via 6ac06e7ca0448682d1a78af175488db743e983fc
